ALTER TABLE documents
    ADD COLUMN IF NOT EXISTS embedded_at TIMESTAMP,
    ADD COLUMN IF NOT EXISTS embedded_chunk_count INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS embedding_status VARCHAR(40) NOT NULL DEFAULT 'NOT_EMBEDDED',
    ADD COLUMN IF NOT EXISTS embedding_error TEXT;
